# Generated by Django 6.0.7 on 2026-07-20 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('suv', 'SUV'), ('truck', 'Truck'), ('bus', 'Bus'), ('other', 'Other')], default='car', max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('year_of_manufacture', models.PositiveIntegerField(blank=True, null=True)),
                ('insurance_valid_upto', models.DateField(blank=True, null=True)),
                ('fitness_certificate_valid_upto', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='branches.branch')),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
    ]
